# Site
name: "Fake Smart"
title: "fake smart"
baseurl: "/fake-smart"
url: "https://amal3ndu.github.io"
description: "A blog for the (artificially) intelligent"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  amalendu:
    name: Amalendu 
    display_name: MLendu
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: amalendubokil@gmail.com
    description: "Hello World! My name is Amalendu"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
