# Site
name: "Fake Smart"
title: "fake smart"
description: "This blog is about artificial intelligence, a.k.a Fake Smarts"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mediumish-theme-jekyll
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  amalendu:
    name: Amalendu 
    display_name: MLendu
    email: amalendubokil@gmail.com
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
